# Generated by Django 2.2 on 2019-07-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=100, verbose_name='预约仪器')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='预约场地')),
            ],
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '预约信息', 'verbose_name_plural': '预约信息'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.CharField(max_length=50, verbose_name='预约日期'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='number',
            field=models.CharField(max_length=50, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='people',
            field=models.CharField(max_length=50, verbose_name='预约人员'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='place',
            field=models.CharField(max_length=50, verbose_name='预约场地、仪器'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='remark',
            field=models.CharField(max_length=1000, verbose_name='其他备注'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.CharField(max_length=100, verbose_name='预约时间'),
        ),
    ]
